title: "Open Source Contributor Guide"
author:
  name: Alexander Osadchy
  email: "alei1180@gmail.com"

description: >
  Open Source Contributor Guide.
  Руководство для контрибьюторов в проекты с открытым исходным кодом.

remote_theme: "jekyll/minima@8106bd4"

minima:
  skin: classic
  nav_pages:
    - README.md
  social_links:
      - title: Open Source Contributor Guide at GitHub
        icon: github
        url: "https://github.com/alei1180/open-source-contributor-guide"
      - title: Telegram channel of the author
        icon: telegram
        url: "https://t.me/alei1180_dev"
